# Generated by Django 3.2 on 2023-11-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted?')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='phone')),
                ('is_natural_person', models.BooleanField(default=True, help_text='طرف حساب شخصی حقیقی است؟', verbose_name='natural person?')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('received_money', models.FloatField(blank=True, default=0, null=True, verbose_name='received money')),
                ('paid_money', models.FloatField(blank=True, default=0, null=True, verbose_name='paid money')),
                ('balance', models.FloatField(blank=True, default=0, help_text='باقی مانده', null=True, verbose_name='balance')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted?')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('received_money', models.FloatField(blank=True, default=0, null=True, verbose_name='received money')),
                ('paid_money', models.FloatField(blank=True, default=0, null=True, verbose_name='paid money')),
                ('balance', models.FloatField(blank=True, default=0, null=True, verbose_name='balance')),
                ('accountside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_tarafhesab', to='core.accountside', verbose_name='accountside')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_user', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ['-accountside'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted?')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted?')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_topics', to='core.subjectcategory', verbose_name='category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topics', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted?')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted?')),
                ('date_time', models.DateTimeField(verbose_name='date time')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='factors/', verbose_name='image')),
                ('is_received_money', models.BooleanField(default=False, verbose_name='is received money')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_expenses', to='core.account', verbose_name='account')),
                ('accountside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountside_expenses', to='core.accountside', verbose_name='accountside')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_expenses', to='core.subject', verbose_name='subject')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_expenses', to='core.workspace', verbose_name='workspace')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='AccountSideCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted?')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.AddField(
            model_name='accountside',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountsides', to='core.accountsidecategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='accountside',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountside_user', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
