# Generated by Django 3.2 on 2023-11-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231110_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(default='', max_length=10000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=400, verbose_name='title'),
            preserve_default=False,
        ),
    ]
