# Generated by Django 4.2.7 on 2023-11-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='change_password',
            field=models.BooleanField(default=False, verbose_name='change password'),
        ),
    ]
