# Generated by Django 4.2.7 on 2023-11-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_role_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='account number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='shaba number'),
        ),
    ]
