# Generated by Django 4.2.7 on 2023-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='paid_money',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='paid money'),
        ),
        migrations.AlterField(
            model_name='account',
            name='received_money',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='received money'),
        ),
    ]
