# Generated by Django 4.2.7 on 2023-11-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_account_balance_alter_account_paid_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_title',
            field=models.CharField(max_length=200, unique=True, verbose_name='account title'),
        ),
    ]
