# Generated by Django 4.2.7 on 2023-11-24 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_account_account_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='paid_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paid money'),
        ),
        migrations.AlterField(
            model_name='account',
            name='received_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='received money'),
        ),
        migrations.AlterField(
            model_name='accountside',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='باقی مانده', null=True, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='accountside',
            name='paid_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paid money'),
        ),
        migrations.AlterField(
            model_name='accountside',
            name='received_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='received money'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date time'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workspace',
            name='accountside',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_accountside', to='core.accountside', verbose_name='accountside'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='paid_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paid money'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='received_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='received money'),
        ),
    ]
