# Generated by Django 4.2.7 on 2023-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_account_balance_alter_account_paid_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17, unique=True, verbose_name='phone'),
        ),
    ]
