# Generated by Django 4.2.7 on 2023-11-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='logout',
            field=models.BooleanField(default=False, verbose_name='logout user'),
        ),
    ]
