# Generated by Django 4.2.7 on 2023-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_role_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='login',
            field=models.BooleanField(default=False, verbose_name='login user'),
        ),
    ]
